import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SideNave from "./components/sideNave";
import { MantineProvider, createTheme } from "@mantine/core";
import "@mantine/core/styles.css";
import { ModalsProvider } from '@mantine/modals';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  /** Your theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <ModalsProvider>
            <header>
              <Header />
            </header>
            <div className="flex pt-4">
              <div className=" border-r-2 w-1/6">
                <SideNave />
              </div>
              <div className=" pl-12 w-full">{children}</div>
            </div>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
